### ISSUE TITLE
Compatibility with 6.4.2/7.0.0 (from 6.3.2)

### ISSUE THREAD

**Issue by codingchili** [codingchili/kibana-mithril#32]
Compatibility
- [x] kibana 7.0.0-alpha1
- [x] kibana 7.0.0-beta1
- [x] kibana 6,4,2

Broken features
- [x] upgrade hapi to v17.
- [x] make sure plugin init can be async as this is required by hapi.register now.
- [x] replace kibana.Plugin with new kibana.Plugin in index.js
- [x] prevent webpack from failing for our .jade files.
- [x] x-pack /login route conflicts with mithril's /login.
- [x] no longer able to register authentication strategy as one already exists.
- [x] the plugin icon is not visible in the menu.
- [x] the plugin page does not render, just prints the template as plain text.
- [x] `__KBN__` is no longer defined, we used it to get the version.
- [x] logging out does not work - set cookie to null has no effect. use unstate?
- [x] cookie is not set when 2FA is activated the first time.

work in progress on branch hapi_upgrade_17.

**Comment by codingchili** [comment]
The issue we are facing during installation with webpack. No idea how to fix this, darn it webpack. leave my files alone.
```
PS C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\bin>
PS C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\bin>  ./kibana-plugin install file:///c:/documents/private/kbn-auth/build/dist/mithril-window
s-x86_64-7.0.0.zip
Attempting to transfer from file:///c:/documents/private/kbn-auth/build/dist/mithril-windows-x86_64-7.0.0.zip
Transferring 22229126 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\node\node.exe C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\src\cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false
(node:22324) Warning: N-API is an experimental feature and could change at any time.
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`

 FATAL  Error: Optimizations failure.
   8177 modules

    ERROR in ./plugins/kibana-mithril/public/app.jade
    Module parse failed: C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\plugins\kibana-mithril\public\app.jade Unexpected token (2:10)
    You may need an appropriate loader to handle this file type.
    | style
    |   include style/style.css
    |   include style/app.css
    |



kibana authentication plugin by codingchili@github init!
{"type":"error","@timestamp":"2019-02-15T21:56:18Z","tags":["warning","process"],"pid":22324,"level":"error","error":{"message":"N-API is an experimental feature and could change at any time.","name":"Warning","stack":"Warning: N-API is an experimental feature and could change at any time.\n    at Object.Module._extensions..node (module.js:681:18)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at bindings (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\plugins\\kibana-mithril\\node_modules\\bindings\\bindings.js:81:44)\n    at Object.<anonymous> (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\plugins\\kibana-mithril\\node_modules\\ref-napi\\lib\\ref.js:7:47)\n    at Module._compile (module.js:652:30)\n    at Module._extensions..js (module.js:663:10)\n    at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\babel-register\\lib\\node.js:152:7)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\plugins\\kibana-mithril\\node_modules\\argon2-ffi\\lib\\index.js:10:16)\n    at Module._compile (module.js:652:30)\n    at Module._extensions..js (module.js:663:10)\n    at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\babel-register\\lib\\node.js:152:7)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (C:/Users/robdu/Downloads/kibana-7.0.0-alpha1-windows-x86_64/plugins/kibana-mithril/src/authentication/hash.js:7:16)\n    at Module._compile (module.js:652:30)\n    at loader (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\babel-register\\lib\\node.js:144:5)"},"message":"N-API is an experimental feature and could change at any time."}
{"type":"log","@timestamp":"2019-02-15T21:56:19Z","tags":["info","optimize"],"pid":22324,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, space_selector, login, logout, logged_out, dashboardViewer, apm, canvas, infra, kibana-mithril and kibana. This may take a few minutes"}
{"type":"log","@timestamp":"2019-02-15T22:01:33Z","tags":["fatal","root"],"pid":22324,"message":"{ Error: Optimizations failure.\n   8177 modules\n    \n    ERROR in ./plugins/kibana-mithril/public/app.jade\n    Module parse failed: C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\plugins\\kibana-mithril\\public\\app.jade Unexpected token (2:10)\n    You may need an appropriate loader to handle this file type.\n    | style\n    |   include style/style.css\n    |   include style/app.css\n    | \n\n    at FsOptimizer.failedStatsToError (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\src\\optimize\\base_optimizer.js:379:27)\n    at compiler.run (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\src\\optimize\\fs_optimizer.js:47:26)\n    at onCompiled (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:241:12)\n    at applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:514:14)\n    at next (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compiler.<anonymous> (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at compilation.seal.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:662:11)\n    at next (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\index.js:282:11\n    at step (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:90:11)\n    at done (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:99:22)\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:105:15\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\worker-farm\\lib\\farm.js:191:19\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n  cause: \n   { Error: Optimizations failure.\n   8177 modules\n    \n    ERROR in ./plugins/kibana-mithril/public/app.jade\n    Module parse failed: C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\plugins\\kibana-mithril\\public\\app.jade Unexpected token (2:10)\n    You may need an appropriate loader to handle this file type.\n    | style\n    |   include style/style.css\n    |   include style/app.css\n    | \n\n    at FsOptimizer.failedStatsToError (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\src\\optimize\\base_optimizer.js:379:27)\n    at compiler.run (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\src\\optimize\\fs_optimizer.js:47:26)\n    at onCompiled (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:241:12)\n    at applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:514:14)\n    at next (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at Compiler.<anonymous> (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:206:13)\n    at compilation.seal.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:195:46)\n    at self.applyPluginsAsync.err (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\webpack\\lib\\Compilation.js:662:11)\n    at next (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\tapable\\lib\\Tapable.js:202:11)\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\index.js:282:11\n    at step (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:90:11)\n    at done (C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:99:22)\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\uglifyjs-webpack-plugin\\dist\\uglify\\index.js:105:15\n    at C:\\Users\\robdu\\Downloads\\kibana-7.0.0-alpha1-windows-x86_64\\node_modules\\worker-farm\\lib\\farm.js:191:19\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n     data: \n      { errors: [Array],\n        warnings: [],\n        version: '3.6.0',\n        hash: 'ad1cbb77aaf2de72cea7',\n        time: 312720,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data: \n   { errors: \n      [ './plugins/kibana-mithril/public/app.jade\\nModule parse failed: C:\\\\Users\\\\robdu\\\\Downloads\\\\kibana-7.0.0-alpha1-windows-x86_64\\\\plugins\\\\kibana-mithril\\\\public\\\\app.jade Unexpected token (2:10)\\nYou may need an appropriate loader to handle this file type.\\n| style\\n|   include style/style.css\\n|   include style/app.css\\n| \\n @ ./plugins/kibana-mithril/public/script/app.js 17:12-54\\n @ ./optimize/bundles/kibana-mithril.entry.js' ],\n     warnings: [],\n     version: '3.6.0',\n     hash: 'ad1cbb77aaf2de72cea7',\n     time: 312720,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     assetsByChunkName: \n      { commons: [Array],\n        kibana: [Array],\n        ml: [Array],\n        infra: 'infra.bundle.js',\n        canvas: [Array],\n        apm: [Array],\n        monitoring: [Array],\n        timelion: 'timelion.bundle.js',\n        graph: 'graph.bundle.js',\n        login: [Array],\n        status_page: 'status_page.bundle.js',\n        space_selector: [Array],\n        logged_out: [Array],\n        'kibana-mithril': 'kibana-mithril.bundle.js',\n        logout: 'logout.bundle.js',\n        stateSessionStorageRedirect: 'stateSessionStorageRedirect.bundle.js',\n        dashboardViewer: 'dashboardViewer.bundle.js',\n        vendors: [Array] },\n     assets: \n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints: \n      { ml: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object],\n        graph: [Object],\n        monitoring: [Object],\n        space_selector: [Object],\n        login: [Object],\n        logout: [Object],\n        logged_out: [Object],\n        dashboardViewer: [Object],\n        apm: [Object],\n        canvas: [Object],\n        infra: [Object],\n        'kibana-mithril': [Object],\n        kibana: [Object] },\n     chunks: \n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     modules: \n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 8077 more items ],\n     filteredModules: 0,\n     children: \n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 49 more items ] },\n  isBoom: true,\n  isServer: true,\n  output: \n   { statusCode: 500,\n     payload: \n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
"
```

**Comment by codingchili** [comment]
base_optimizer.js in kibana specifies some rules for webpack. not sure how to modify these.

.html and .tmpl uses a raw-loader, which sounds like something that should be able to handle our jade templates. renamed .jade templates to .tmpl and now it "works".

**Comment by codingchili** [comment]
changed /login route to /mithril to avoid conflicts.
new issue: we can no longer register a default authentication strategy, because one already exists now. happy times.

**Comment by codingchili** [comment]
```
log   [09:07:28.149] [fatal][root] { AssertionError [ERR_ASSERTION]: Cannot set default strategy more than once
    at module.exports.internals.Auth.default (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\node_modules\hapi\lib\auth.js:73:14)
    at Plugin.init [as externalInit] (C:/Users/robdu/Downloads/kibana-7.0.0-alpha1-windows-x86_64/plugins/kibana-mithril/index.js:71:17)
    at Object.register (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\src\server\plugins\lib\plugin.js:72:20)
    at internals.Server.register (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\node_modules\hapi\lib\server.js:431:35)
    at Plugin.init (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\src\server\plugins\lib\plugin.js:76:28)
    at Plugin.init (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\node_modules\lodash\index.js:7407:25)
    at callPluginHook (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\src\server\plugins\lib\call_plugin_hook.js:37:25)
    at callHookOnPlugins (C:\Users\robdu\Downloads\kibana-7.0.0-alpha1-windows-x86_64\src\server\plugins\initialize_mixin.js:28:37)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

this is a major issue because the plugin depends on being able to set this. if this doesn't work this plugin cannot be used.

**Comment by codingchili** [comment]
we can now set the default strategy again, using 
```
server.auth.settings.default = null;
```

From where we set up our strategies. This little trick clears the default authentication strategy and the assertions pass when we set it using the public API.

**Comment by codingchili** [comment]
make sure to check package.json version of kibana, 7.0.0 does not pass the XSRF filter for the alpha1 version. We need to set it to exactly what's in kibanas package.json. For 7.0.0 alpha1 this is "7.0.0-alpha1".

If not - requests will fail with a 401 and the message "'Browser client is out of date, please refresh the page'".

**Comment by codingchili** [comment]
Changes made when upgrading to HAPI v17.

- await server.register
- replace (request, reply) with (request, h) -> h might stand for helper? its a part of the hapi 'toolkit'.
- made plugin init async so we can await server.register
- all routes must now return a promise, or use return h.response().code(...)

**Comment by codingchili** [comment]
information on why the icon is not loading, they changed it to an EUI/svg. Looks like we should use the "image" property now instead of the "icon" property.

https://www.elastic.co/blog/kibana-plugin-api-changes-in-6-5

**Comment by codingchili** [comment]
replaced app.jade with app.html, an error now appears when loading the app.

```
Uncaught SyntaxError: Unexpected token : (http://localhost:5601/app/kibana-mithril#?_g=():1)
Version: 7.0.0-alpha1
Build: 21216
Error: Uncaught SyntaxError: Unexpected token : (http://localhost:5601/app/kibana-mithril#?_g=():1)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js:3:857477)
    at DOMEval (http://localhost:5601/bundles/vendors.bundle.js:284:1125)
    at Function.globalEval (http://localhost:5601/bundles/vendors.bundle.js:284:3584)
    at text script (http://localhost:5601/bundles/vendors.bundle.js:295:120679)
    at ajaxConvert (http://localhost:5601/bundles/vendors.bundle.js:295:110440)
    at done (http://localhost:5601/bundles/vendors.bundle.js:295:115886)
    at XMLHttpRequest.<anonymous> (http://localhost:5601/bundles/vendors.bundle.js:295:119777)
    at Object.send (http://localhost:5601/bundles/vendors.bundle.js:295:120266)
    at Function.ajax (http://localhost:5601/bundles/vendors.bundle.js:295:115376)
    at Function.jQuery._evalUrl (http://localhost:5601/bundles/vendors.bundle.js:295:117487)
    at domManip (http://localhost:5601/bundles/vendors.bundle.js:295:68636)
    at jQuery.fn.init.append (http://localhost:5601/bundles/vendors.bundle.js:295:70707)
    at jQuery.fn.init.<anonymous> (http://localhost:5601/bundles/vendors.bundle.js:295:72218)
    at access (http://localhost:5601/bundles/vendors.bundle.js:295:45007)
    at jQuery.fn.init.html (http://localhost:5601/bundles/vendors.bundle.js:295:71790)
    at Object.link (http://localhost:5601/bundles/vendors.bundle.js:328:7179)
```

**Comment by codingchili** [comment]
removed script and style imports from the app.html template and moved imports into the app.js.
The plugin app is now loading.

Logout button does not work since __KBN_ is not defined anymore, we need the version in order for the POST to succeed.

**Comment by codingchili** [comment]
when using $http from angular the kbn-version header appears to be set already.

**Comment by codingchili** [comment]
to unset the token cookie we need to specify a path when calling state/unstate. Using the same options object and now we can unset the cookie.

**Comment by codingchili** [comment]
Now working again. 

Lets make a release.
